#!/usr/bin/env python3
"""Plot a confusion matrix generated by make_confusion_csv.py."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def load_matrix(path: Path) -> tuple[list[str], list[list[float]]]:
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.reader(handle))
    if len(rows) < 2 or len(rows[0]) < 2:
        raise ValueError(f"Invalid confusion matrix: {path}")
    labels = rows[0][1:]
    matrix = [[float(value) for value in row[1:]] for row in rows[1:]]
    if len(matrix) != len(labels) or any(len(row) != len(labels) for row in matrix):
        raise ValueError("Confusion matrix must be square")
    return labels, matrix


def normalize_rows(matrix: list[list[float]]) -> list[list[float]]:
    normalized: list[list[float]] = []
    for row in matrix:
        total = sum(row)
        normalized.append([value / total if total else 0.0 for value in row])
    return normalized


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("confusion_csv", type=Path)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--normalize", action="store_true")
    args = parser.parse_args()

    labels, matrix = load_matrix(args.confusion_csv)
    display_matrix = normalize_rows(matrix) if args.normalize else matrix
    out_path = args.out or args.confusion_csv.with_suffix(".png")

    size = max(10, len(labels) * 0.6)
    plt.figure(figsize=(size, size))
    plt.imshow(display_matrix, interpolation="nearest")
    plt.title(args.confusion_csv.stem + (" (row-normalized)" if args.normalize else ""))
    plt.xlabel("Predicted label")
    plt.ylabel("True label")
    plt.xticks(range(len(labels)), labels, rotation=90)
    plt.yticks(range(len(labels)), labels)
    plt.colorbar()

    for row_index, row in enumerate(display_matrix):
        for column_index, value in enumerate(row):
            if value:
                text = f"{value:.2f}" if args.normalize else str(int(value))
                plt.text(column_index, row_index, text, ha="center", va="center", fontsize=7)

    plt.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(out_path, dpi=200)
    plt.close()
    print(f"Saved {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
